import type { CapitalEvent, Company, CompanyRelationship } from '../data/types';
import { formatChange, formatMarketCap, formatTime } from '../lib/format';

const lifecycleLabels: Record<CapitalEvent['state'], string> = { new: '新发生', developing: '发酵', diverging: '分歧', cooling: '降温', ended: '结束' };

type Props = { event: CapitalEvent | null; company: Company | null; companies: Company[]; relationships: CompanyRelationship[]; onCompany: (company: Company) => void; onClose: () => void; onReplay: () => void };

export default function DetailPanel(props: Props) {
  return <aside className="detail-panel" aria-label="详情面板">{props.event ? <EventDetail {...props} event={props.event} /> : props.company ? <CompanyDetail company={props.company} companies={props.companies} relationships={props.relationships} onClose={props.onClose} /> : <EmptyDetail />}</aside>;
}

function EventDetail({ event, companies, onCompany, onClose, onReplay }: Props & { event: CapitalEvent }) {
  const relatedCompanies = event.companyIds.map((id) => companies.find((company) => company.id === id)).filter((company): company is Company => Boolean(company));
  const countries = Array.from(new Set(relatedCompanies.map((company) => company.country))).slice(0, 4);
  return <div className="detail-inner"><div className="detail-overline"><span className="signal-icon">↗</span><span>EVENT INTELLIGENCE</span><button className="detail-close" onClick={onClose} aria-label="关闭详情">×</button></div><h2>{event.title}</h2><p className="detail-summary">{event.summary}</p><div className="event-location"><span className="location-pin">⌖</span><span><b>{event.location}</b><small>{formatTime(event.occurredAt)} · {event.sourceCount} 个新闻来源</small></span></div><div className="detail-metrics"><div><span>热度</span><strong className="metric-hot">{event.heat}</strong><small>CAPITAL SIGNAL</small></div><div><span>重要程度</span><strong>{event.importance === 'high' ? '高' : event.importance === 'medium' ? '中' : '低'}</strong><small>MARKET IMPACT</small></div><div><span>生命周期</span><strong>{lifecycleLabels[event.state]}</strong><small>EVENT STATUS</small></div></div><div className="detail-section"><div className="section-label">关联公司 <span>{relatedCompanies.length} 家</span></div><div className="related-companies">{relatedCompanies.map((company) => <button key={company.id} onClick={() => onCompany(company)}><span className="company-avatar">{company.shortName.slice(0, 1)}</span><span><b>{company.shortName}</b><small>{company.ticker} · {company.exchange}</small></span><em className={company.priceChange >= 0 ? 'positive' : 'negative'}>{formatChange(company.priceChange)}</em></button>)}</div></div>{countries.length > 1 && <div className="detail-section impact-section"><div className="section-label">传播路径 <span>市场联动</span></div><div className="impact-path">{countries.map((country, index) => <span key={country}>{index > 0 && <i>→</i>}<b>{country}</b></span>)}</div></div>}<button className="detail-cta" onClick={onReplay}>播放存储产业完整回放 <span>→</span></button></div>;
}

function CompanyDetail({ company, relationships, companies, onClose }: { company: Company; relationships: CompanyRelationship[]; companies: Company[]; onClose: () => void }) {
  const related = relationships.filter((relation) => relation.sourceCompanyId === company.id || relation.targetCompanyId === company.id);
  return <div className="detail-inner"><div className="detail-overline"><span className="signal-icon">✦</span><span>COMPANY PROFILE</span><button className="detail-close" onClick={onClose} aria-label="关闭详情">×</button></div><div className="company-profile-title"><div className="company-logo">{company.shortName.slice(0, 1)}</div><div><h2>{company.shortName}</h2><p>{company.name}</p></div></div><div className="ticker-row"><span>{company.ticker}</span><span>{company.exchange}</span><span className={company.marketStatus === 'open' ? 'market-open' : 'market-closed'}>● {company.marketStatus === 'open' ? '交易中' : company.marketStatus === 'preopen' ? '盘前' : '已收市'}</span></div><div className="price-block"><strong>{formatMarketCap(company.marketCap)}</strong><span className={company.priceChange >= 0 ? 'positive' : 'negative'}>{formatChange(company.priceChange)} 今日</span></div><div className="mini-chart" role="img" aria-label={`${company.shortName}示意行情走势`}><span /><span /><span /><span /><span /><span /><span /><i /></div><div className="company-facts"><div><span>总部</span><b>{company.city} · {company.country}</b></div><div><span>行业</span><b>{company.industry}</b></div><div><span>市场活跃度</span><b>{company.activity}<small>/ 100</small></b></div></div><div className="detail-section"><div className="section-label">产业关系 <span>{related.length} 条</span></div><div className="relation-list">{related.length ? related.map((relation) => { const otherId = relation.sourceCompanyId === company.id ? relation.targetCompanyId : relation.sourceCompanyId; const other = companies.find((item) => item.id === otherId); return <div key={relation.id}><span className="relation-arrow">↗</span><span><b>{other?.shortName ?? '未知公司'}</b><small>{relation.description}</small></span><em>{relation.type}</em></div>; }) : <div className="relation-empty">当前主题下暂无直接关系</div>}</div></div></div>;
}

function EmptyDetail() { return <div className="empty-detail"><div className="empty-cross">＋</div><span>选择地球上的公司或事件</span><small>DETAIL VIEW / SELECT A SIGNAL</small></div>; }
